[package]
name = "ir"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.5.0", features = [
  "llvm18-0",
  "llvm18-0-prefer-dynamic",
] }
preprocessor = { path = "../preprocessor" }
common = { path = "../common" }
