use common::constants::keywords::{
    DECLARATION_CONSTANT, DECLARATION_FUNCTION, DECLARATION_VARIABLE, STATEMENT_ELSE, STATEMENT_IF,
    STATEMENT_RETURN, STATEMENT_WHILE,
};

pub const KEYWORDS: &[&str] = &[
    DECLARATION_CONSTANT,
    DECLARATION_FUNCTION,
    DECLARATION_VARIABLE,
    STATEMENT_IF,
    STATEMENT_ELSE,
    STATEMENT_WHILE,
    STATEMENT_RETURN,
];
