[package]
name = "starbloom"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
ir = { path = "../ir" }
inkwell = { version = "0.5.0", features = [
  "llvm18-0",
  "llvm18-0-prefer-dynamic",
] }
